import Head from "next/head";
import HomeBase from "./homeBase";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pokemon Catch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/pokeball.png" />
      </Head>
      <HomeBase />
    </>
  );
}
